sudo: required
services:
  - docker
language: node_js
node_js:
  - 6
cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
before_script:
  - npm install -g mocha
script:
  - npm test
  - npm run build
after_script:
  - docker build -t arashcuzi/testdocker .
  - docker run -d -p 9000:9000 arashcuzi/testdocker
